version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyu/data/mariadb
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/changhyu/data/wordpress